from sqlalchemy import Column, Boolean, Text

from app.db.database import Base
class PartnerPersonalityTraitsScore(Base):
    __tablename__ = "partner_personality_traits_score"

    user_id = Column(Text, primary_key=True, nullable=False)
    partner_active_listener = Column(Boolean, default=False)
    partner_adventurous = Column(Boolean, default=False)
    partner_affectionate = Column(Boolean, default=False)
    partner_ambitious = Column(Boolean, default=False)
    partner_animal_lover = Column(Boolean, default=False)
    partner_assertive = Column(Boolean, default=False)
    partner_bookworm = Column(Boolean, default=False)
    partner_brunch_lover = Column(Boolean, default=False)
    partner_carefree = Column(Boolean, default=False)
    partner_charismatic = Column(Boolean, default=False)
    partner_cheerful = Column(Boolean, default=False)
    partner_competitive = Column(Boolean, default=False)
    partner_confident = Column(Boolean, default=False)
    partner_conservative = Column(Boolean, default=False)
    partner_creative = Column(Boolean, default=False)
    partner_cultural = Column(Boolean, default=False)
    partner_enfj = Column(Boolean, default=False)
    partner_enfp = Column(Boolean, default=False)
    partner_entj = Column(Boolean, default=False)
    partner_entp = Column(Boolean, default=False)
    partner_esfj = Column(Boolean, default=False)
    partner_esfp = Column(Boolean, default=False)
    partner_estj = Column(Boolean, default=False)
    partner_estp = Column(Boolean, default=False)
    partner_empathetic = Column(Boolean, default=False)
    partner_entrepreneurial = Column(Boolean, default=False)
    partner_extroverted = Column(Boolean, default=False)
    partner_family_oriented = Column(Boolean, default=False)
    partner_fashionable = Column(Boolean, default=False)
    partner_funny = Column(Boolean, default=False)
    partner_generous = Column(Boolean, default=False)
    partner_germaphobe = Column(Boolean, default=False)
    partner_good_with_kids = Column(Boolean, default=False)
    partner_infj = Column(Boolean, default=False)
    partner_infp = Column(Boolean, default=False)
    partner_intj = Column(Boolean, default=False)
    partner_intp = Column(Boolean, default=False)
    partner_isfj = Column(Boolean, default=False)
    partner_isfp = Column(Boolean, default=False)
    partner_istj = Column(Boolean, default=False)
    partner_istp = Column(Boolean, default=False)
    partner_intelligent = Column(Boolean, default=False)
    partner_introverted = Column(Boolean, default=False)
    partner_liberal = Column(Boolean, default=False)
    partner_nerdy = Column(Boolean, default=False)
    partner_night_owl = Column(Boolean, default=False)
    partner_open_minded = Column(Boolean, default=False)
    partner_outdoorsy = Column(Boolean, default=False)
    partner_patient = Column(Boolean, default=False)
    partner_playful = Column(Boolean, default=False)
    partner_positive = Column(Boolean, default=False)
    partner_respectful = Column(Boolean, default=False)
    partner_romantic = Column(Boolean, default=False)
    partner_self_aware = Column(Boolean, default=False)
    partner_shopaholic = Column(Boolean, default=False)
    partner_spontaneous = Column(Boolean, default=False)
    partner_thoughtful = Column(Boolean, default=False)
    partner_adaptable = Column(Boolean, default=False)
    partner_compassionate = Column(Boolean, default=False)
    partner_detail_oriented = Column(Boolean, default=False)
    partner_easygoing = Column(Boolean, default=False)
    partner_flexible = Column(Boolean, default=False)
    partner_laid_back = Column(Boolean, default=False)
    partner_optimistic = Column(Boolean, default=False)
    partner_punctual = Column(Boolean, default=False)
    partner_resourceful = Column(Boolean, default=False)
    partner_resilient = Column(Boolean, default=False)
    partner_sincere = Column(Boolean, default=False)
    partner_tactful = Column(Boolean, default=False)
    